<?php

/**
 * @file
 * This module implements SBSYS ESDH backend for use in os2web
 */

define('OS2WEB_SBSYS_ESDH_CASES_IMPORT_DIR', 'public://sbsys/cp');

function os2web_sbsys_esdh_cases_import_fixed_case_field_values() {
  return array(
    'Sagstype - Sagstype' => 'BYGGESAG',
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Register as provider of esdh plugins
 */
function os2web_sbsys_esdh_cases_import_ctools_plugin_directory($module, $plugin) {
  if ($module == 'os2web_esdh_provider') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_menu().
 */
function os2web_sbsys_esdh_cases_import_menu() {
  $items['admin/config/os2web/esdh_provider/sbsys_cases_import'] = array(
    'title' => 'SBSYS Cases import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_sbsys_esdh_cases_import_form'),
    'access arguments' => array('administer os2web'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'os2web_sbsys_esdh_cases_import.admin.inc',
  );
  $items['admin/config/os2web/esdh_provider/sbsys_cases_import/confirm'] = array(
    'title' => 'SBSYS Cases import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_sbsys_esdh_cases_import_form_confirm'),
    'access arguments' => array('administer os2web'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'os2web_sbsys_esdh_cases_import.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_form_alter().
 *
 * Add configuration to the settings form.
 */
function os2web_sbsys_esdh_cases_import_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  $form['sbsys-cases-import'] = array(
    '#type' => 'fieldset',
    '#title' => 'SBSYS Case Publishing import settings',
    '#collapsible' => TRUE,
    '#collapsed' => empty(variable_get('os2web_sbsys_esdh_cases_import_path')),
  );
  $form['sbsys-cases-import']['os2web_sbsys_esdh_cases_import_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Path for SBSYS publish folder.',
    '#description' => 'Path with schema where SBSYS ESDH will publish files. Example: ' . OS2WEB_SBSYS_ESDH_CASES_IMPORT_DIR,
    '#default_value' => variable_get('os2web_sbsys_esdh_cases_import_path', OS2WEB_SBSYS_ESDH_CASES_IMPORT_DIR),
  );
//
//  // Case fields mapping.
//  $form['sbsys-cases-import']['os2web_sbsys_esdh_cases_import_case_fields_mapping'] = array(
//    '#type' => 'fieldset',
//    '#title' => 'Case fields mapping',
//    '#tree' => TRUE,
//    '#collapsible' => TRUE,
//    '#collapsed' => empty(variable_get('os2web_sbsys_esdh_cases_import_case_fields_mapping')),
//  );
//
//  $case_fields_mapping = variable_get('os2web_sbsys_esdh_cases_import_case_fields_mapping', array());
//
//  // Get default keys.
//  if (empty($case_fields_mapping)) {
//    $case_fields_mapping = _os2web_sbsys_esdh_cases_import_get_case_default_mapping_keys();
//  }
//
//  // Remove key with fixed values.
//  $case_fields_mapping = array_diff_key($case_fields_mapping, array_flip(array_keys(os2web_sbsys_esdh_cases_import_fixed_case_field_values())));
//
//  foreach ($case_fields_mapping as $mapping_key => $mapping_value) {
//    $form['sbsys-cases-import']['os2web_sbsys_esdh_cases_import_case_fields_mapping'][$mapping_key] = array(
//      '#type' => 'textfield',
//      '#title' => $mapping_key,
//      '#default_value' => $mapping_value,
//    );
//  }
//
//  // Document fields mapping.
//  $form['sbsys-cases-import']['os2web_sbsys_esdh_cases_import_document_fields_mapping'] = array(
//    '#type' => 'fieldset',
//    '#title' => 'Documents fields mapping',
//    '#tree' => TRUE,
//    '#collapsible' => TRUE,
//    '#collapsed' => empty(variable_get('os2web_sbsys_esdh_cases_import_document_fields_mapping')),
//  );
//
//  $document_fields_mapping = variable_get('os2web_sbsys_esdh_cases_import_document_fields_mapping', array());
//  if (empty($document_fields_mapping)) {
//    $default_document = os2web_cp_service_default_document();
//    $document_fields_mapping = $default_document['fields'];
//  }
//  foreach ($document_fields_mapping as $mapping_key => $mapping_value) {
//    $form['sbsys-cases-import']['os2web_sbsys_esdh_cases_import_document_fields_mapping'][$mapping_key] = array(
//      '#type' => 'textfield',
//      '#title' => $mapping_key,
//      '#default_value' => $mapping_value,
//    );
//  }
}

/**
 * Loads the JSONPath library.
 *
 * @return bool
 *   Result of loading library.
 */
function _os2web_sbsys_esdh_cases_import_load_json_path_library() {
  if (function_exists('jsonPath')) {
    return TRUE;
  }
  
  $libraries_path = module_exists('libraries') ? libraries_get_path('jsonpath') : FALSE;
  if ($libraries_path && is_dir($libraries_path)) {
    $path = $libraries_path;
  }
  elseif (is_dir(DRUPAL_ROOT . '/sites/all/libraries/jsonpath')) {
    $path = DRUPAL_ROOT . '/sites/all/libraries/jsonpath';
  }
  else {
    return FALSE;
  }

  $files = glob($path . '/jsonpath*.php');
  if (empty($files)) {
    return FALSE;
  }

  require_once reset($files);
  return function_exists('jsonPath');
}

/**
 * Imports cases.
 *
 * @param $case
 * @param bool $force
 */
function _os2web_sbsys_esdh_cases_import_case($case, $force = FALSE) {
  $case_data = os2web_esdh_provider_invoke('cm', 'get_case_data', $case['uri']);

  // Return with errors reporting.
  if (!empty($case_data['errors'])) {
    if (drupal_is_cli()) {
      watchdog('os2web_sbsys_esdh_cases_import', implode("\n", $case_data['errors']), array(), WATCHDOG_WARNING);
    }
    else {
      drupal_set_message(implode("\n", $case_data['errors']), 'error');
    }
    return;
  }
  
  $existing_case = os2web_esdh_provider_invoke('cm', 'lookup_case', $case['id']);
  if (empty($existing_case) || $force) {
    $case_fields_mapping = _os2web_sbsys_esdh_cases_import_get_case_default_mapping_keys();
    $publication = array(
      'fields' => os2web_sbsys_esdh_cases_import_fixed_case_field_values(),
    );
    foreach ($case_fields_mapping as $field_name => $field_mapping) {
      $value = jsonPath($case_data['data'], $field_mapping);
      if (isset($value[0]) && !empty(trim($value[0]))) {
        $publication['fields'][$field_name] = $value[0];
      }
    }
    os2web_cp_service_create_case($publication);
  }
}

function _os2web_sbsys_esdh_cases_import_get_case_default_mapping_keys() {
  $mapping_keys = array(
    'Sagstitel' => 'Titel',
    'SagsID' => 'Id',
    'SystemID' => 'Id',
    'Sagsnummer' => 'Sagsnummer',
    'Matrikel' => 'Matrikler[0].Id',
    'Ejendomsnummer' => 'Ejendomme[0].EjendomsNummer',
    'Sagsstatus - Sagstypebetegnelse' => 'Sagsstatus',
    'Sagsbehandler - BrugerID' => 'Sagsbehandler[0].Id',
    'Sagsbehandler - Brugernavn' => 'Sagsbehandler[0].Navn',
  );

  return $mapping_keys;
}
