<?php

/**
 * @file
 * Code for the OS2Web Bygge Cases feature.
 */

include_once 'os2web_bygge_cases.features.inc';

/**
 * Implements hook_block_info().
 */
function os2web_bygge_cases_block_info() {
  $blocks['os2web_bygge_cases_menu'] = array(
    // info: The name of the block.
    'info' => t('NemID login block'),
    'cache' =>  DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function os2web_bygge_cases_block_view($delta = '') {
  $block = array();

  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'os2web_bygge_cases_menu':
      if ($pid = os2web_nemlogin_auth_get_pid()) {
        $output = t('Logged in with NemID, click <a href="@login_url">here</a> to logout', array('@login_url' => url('os2web_nemlogin_logout')));
        $output .= ' PID: ' . $pid;
      } else {
        $output = nemlogin_link('Login med Nemlogin', NULL, array('attributes' => array('class' => array('btn', 'btn-secondary'))));
      }

      // Create your block content here
      $block['subject'] = t('NemID login');
      $block['content'] = array(
        '#markup' => $output
      );

      break;
  }

  return $block;
}

/**
 * Implements hook_node_access().
 */
function os2web_bygge_cases_node_access($node, $op, $account) {
  if ($op == 'view') {
    $type = is_string($node) ? $node : $node->type;
    if ($type == 'os2web_cp_service_cp_case') {

      $field_os2web_cp_service_cpr_nr = field_get_items('node', $node, 'field_os2web_cp_service_pid_nr');
      $field_os2web_cp_service_cvr_nr = field_get_items('node', $node, 'field_os2web_cp_service_cvr_nr');
      if (!empty($field_os2web_cp_service_cpr_nr) && !empty($field_os2web_cp_service_cvr_nr)) {
        $owners_cpr_cvr_nr =array_merge($field_os2web_cp_service_cpr_nr, $field_os2web_cp_service_cvr_nr);
      }
      else {
        $owners_cpr_cvr_nr = !empty($field_os2web_cp_service_cpr_nr) ? $field_os2web_cp_service_cpr_nr : $field_os2web_cp_service_cvr_nr;
      }
      $cpr = os2web_nemlogin_auth_get_value('cpr');
      $cvr = os2web_nemlogin_auth_get_value('cvr');
      $person_nr = is_null($cpr) ? $cvr : $cpr;
      // Doing check only if limit PID are set.
      if (!empty($owners_cpr_cvr_nr)) {

        // CRP/CVR not present, denying access.
        if (!$person_nr) {
          return NODE_ACCESS_DENY;
        }

        // If match is found, not restricting the access.
        foreach ($owners_cpr_cvr_nr as $cpr_nr) {
          if (str_replace('-', '', $cpr_nr['value']) == $person_nr) {
            return NODE_ACCESS_IGNORE;
          }
        }
        // No match is found, denying access.
        return NODE_ACCESS_DENY;
      }
      return NODE_ACCESS_IGNORE;
    }
    elseif ($type == 'os2web_cp_service_cp_document') {
      $case_id = NULL;

      // Letting parent case decide the access permission.
      $field_os2web_cp_service_case_id = field_get_items('node', $node, 'field_os2web_cp_service_case_id');
      if (is_array($field_os2web_cp_service_case_id)) {
        $case_id = $field_os2web_cp_service_case_id[0]['value'];
      }

      if ($case_id) {
        $case = _os2web_cp_service_get_cp_document_node_by_case_id($case_id);
        if ($case) {
          if (!node_access($op, $case, $account)) {
            return NODE_ACCESS_DENY;
          }
        }
      }
    }
  }

  return NODE_ACCESS_IGNORE;
}


function os2web_bygge_cases_user_can_see_case($nid) {
  $case = node_load($nid);
  if (!node_access('view', $case)){
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_preprocess_node().
 */
function os2web_bygge_cases_preprocess_node(&$variables) {
  if ($variables['type'] == 'os2web_cp_service_cp_case') {
    $variables['content']['#cp_case_documents'] = views_embed_view('os2web_cp_service_cp_case_view', 'attachment_1', $variables['nid']);
  }
}

function os2web_bygge_cases_user_can_see_cases_by_address($tid) {
  global $user;
  $bfe_numbers = os2web_nemlogin_auth_get_value('bfe_numbers');
  $term = taxonomy_term_load($tid);
  if ($user->uid == 1) {
    return TRUE;
  }
  if (isset($term->field_cp_service_tax_addr_bfe_nr[LANGUAGE_NONE]) && in_array($term->field_cp_service_tax_addr_bfe_nr[LANGUAGE_NONE][0]['value'], $bfe_numbers)){
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_views_pre_render().
 */
function os2web_bygge_cases_views_pre_render(&$view) {
  if ($view->name == 'os2web_bygge_case_cases' && $view->current_display == 'bygge_cases') {
    $args = arg();
    $term = taxonomy_term_load($args[1]);
    $view->build_info['title'] = t('Byggesager på %address', array('%address' => $term->name));
  }
}
